name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python manage.py test --noinput

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Debug secrets
        run: |
          echo "USERNAME_EXISTS=${{ secrets.DOCKERHUB_USERNAME != '' }}" >> $GITHUB_ENV
          echo "TOKEN_EXISTS=${{ secrets.DOCKERHUB_TOKEN != '' }}" >> $GITHUB_ENV
          echo "USERNAME_VALUE=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
      - name: Show debug info
        run: |
          echo "Username exists: $USERNAME_EXISTS"
          echo "Token exists: $TOKEN_EXISTS"
          echo "Username value: $USERNAME_VALUE"
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: docker.io/krame1s/django-girls-practice:main

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Debug secrets
        run: |
          echo "USERNAME_EXISTS=${{ secrets.DOCKERHUB_USERNAME != '' }}" >> $GITHUB_ENV
          echo "TOKEN_EXISTS=${{ secrets.DOCKERHUB_TOKEN != '' }}" >> $GITHUB_ENV
          echo "USERNAME_VALUE=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
      - name: Show debug info
        run: |
          echo "Username exists: $USERNAME_EXISTS"
          echo "Token exists: $TOKEN_EXISTS"
          echo "Username value: $USERNAME_VALUE"
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker pull docker.io/krame1s/django-girls-practice:main
          docker tag docker.io/krame1s/django-girls-practice:main docker.io/krame1s/django-girls-practice:latest
          docker push docker.io/krame1s/django-girls-practice:latest
